apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}
spec:
  containers:
  - name: {{ .Values.name }}
    image: {{ .Values.image_name }}:{{ .Values.image_semver }}
    imagePullPolicy: Always
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    env:
    - name: BOOTSTRAP_SERVERS
      value: {{ .Values.kafka_server }}
    - name: SOURCE_TOPIC
      value: {{ .Values.source_topic }}
    - name: TARGET_TOPIC
      value: {{ .Values.target_topic }}
    - name: CONTAINER_NAME
      value: {{ .Values.container_name }}
    - name: FOLDER_NAME
      value: {{ .Values.folder_name }}
    - name: FILE_NAME
      value: {{ .Values.file_name }}
    - name: EVENTHUB_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: eventhub-connection-string
          key: secret
    - name: BLOB_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: blob-connection-string
          key: secret
    livenessProbe:
      exec:
        # Check if the mapper script is still running
        command: ["pgrep", "-fl", "mapper.py"]
      initialDelaySeconds: 30
      periodSeconds: 10