namespace: dsi-data-pipelines
name: dsi-eqbd-mapper-extractor
aws_act_no: "647746917454"
deployment: AZURE
env: eso-nonprod
kafka_server: eventhub-mesh-dpn-sbx-uksouth-001.servicebus.windows.net:9093
source_topic: dsi-eqbd-consumer-valid-schema
target_topic: dsi-eqbd-consumer-exported-data
container_name: dsi-dry-run
folder_name: dsi-eqbd-extractor
file_name: EQBD_export.xml
image_name: acrmeshdpnsbxuksouth001.azurecr.io/dsi/mapper-consumer-extractor-eqbd
image_semver: latest
